name: Publish Game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MinGW
      run: choco install mingw -y

    - name: Add MinGW to PATH
      run: |
        setx PATH "%PATH%;C:\tools\mingw64\bin"
        refreshenv

    - name: Install MSYS2
      run: choco install msys2 -y
      
    - name: Set up MSYS2
      run: |
        refreshenv
        ridk install 3
        pacman -Sy --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-allegro

    - name: Install Allegro
      run: |
        pacman -Sy --noconfirm
        pacman -S --noconfirm mingw-w64-x86_64-allegro

    - name: Verify MinGW installation
      run: |
        gcc --version
        g++ --version

    - name: Run build script
      run: scripts\compiler.bat

    - name: Upload compiled game
      uses: actions/upload-artifact@v3
      with:
        name: compiled-game
        path: bin\game.exe